import type { Metadata } from "next";
import "./globals.css";
import AdminShortcutListener from "@/components/AdminShortcutListener";
import { brandFont, navFont, headingFont, subheadingFont, bodyFont, buttonFont } from "./fonts";

export const metadata: Metadata = {
  title: "GeniusLand",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="uk"
      className={`${brandFont.variable} ${navFont.variable} ${headingFont.variable} ${subheadingFont.variable} ${bodyFont.variable} ${buttonFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AdminShortcutListener />
        {children}
      </body>
    </html>
  );
}
